name = "multitenant-dashboard"
main = "src/index.tsx"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]

[env.production]
workers_dev = true

[[d1_databases]]
binding = "DB"  # Available in your Worker as env.DB
database_name = "multitenant_db"
database_id = "5ce22099-5df5-49f3-8e0f-f9a312576deb"  # Get this from wrangler d1 create
migrations_dir = "./migrations"

[vars]
ENVIRONMENT = "production"